#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coder.CompilerOfOJ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Coder.Db")]
	public partial class CompileLtoSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCompileCacheModels(CompileCacheModels instance);
    partial void UpdateCompileCacheModels(CompileCacheModels instance);
    partial void DeleteCompileCacheModels(CompileCacheModels instance);
    partial void InsertResultModels(ResultModels instance);
    partial void UpdateResultModels(ResultModels instance);
    partial void DeleteResultModels(ResultModels instance);
    partial void InsertBaseProblemModels(BaseProblemModels instance);
    partial void UpdateBaseProblemModels(BaseProblemModels instance);
    partial void DeleteBaseProblemModels(BaseProblemModels instance);
    partial void InsertSingleResultModels(SingleResultModels instance);
    partial void UpdateSingleResultModels(SingleResultModels instance);
    partial void DeleteSingleResultModels(SingleResultModels instance);
    partial void InsertTeamResultModels(TeamResultModels instance);
    partial void UpdateTeamResultModels(TeamResultModels instance);
    partial void DeleteTeamResultModels(TeamResultModels instance);
    #endregion
		
		public CompileLtoSDataContext() : 
				base(global::Coder.CompilerOfOJ.Properties.Settings.Default.Coder_DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CompileLtoSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompileLtoSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompileLtoSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompileLtoSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CompileCacheModels> CompileCacheModels
		{
			get
			{
				return this.GetTable<CompileCacheModels>();
			}
		}
		
		public System.Data.Linq.Table<ResultModels> ResultModels
		{
			get
			{
				return this.GetTable<ResultModels>();
			}
		}
		
		public System.Data.Linq.Table<BaseProblemModels> BaseProblemModels
		{
			get
			{
				return this.GetTable<BaseProblemModels>();
			}
		}
		
		public System.Data.Linq.Table<SingleResultModels> SingleResultModels
		{
			get
			{
				return this.GetTable<SingleResultModels>();
			}
		}
		
		public System.Data.Linq.Table<TeamResultModels> TeamResultModels
		{
			get
			{
				return this.GetTable<TeamResultModels>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompileCacheModels")]
	public partial class CompileCacheModels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cacheCodeId;
		
		private string _codeType;
		
		private string _cacheCodeFileName;
		
		private int _memoryLimit;
		
		private int _timeLimit;
		
		private int _uid;
		
		private int _problemId;
		
		private System.Nullable<int> _contentId;
		
		private int _resultId;
		
		private byte _isTeamContest;
		
		private byte _isSingleContest;
		
		private System.DateTime _submitTime;
		
		private int _codePriority;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncacheCodeIdChanging(int value);
    partial void OncacheCodeIdChanged();
    partial void OncodeTypeChanging(string value);
    partial void OncodeTypeChanged();
    partial void OncacheCodeFileNameChanging(string value);
    partial void OncacheCodeFileNameChanged();
    partial void OnmemoryLimitChanging(int value);
    partial void OnmemoryLimitChanged();
    partial void OntimeLimitChanging(int value);
    partial void OntimeLimitChanged();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnproblemIdChanging(int value);
    partial void OnproblemIdChanged();
    partial void OncontentIdChanging(System.Nullable<int> value);
    partial void OncontentIdChanged();
    partial void OnresultIdChanging(int value);
    partial void OnresultIdChanged();
    partial void OnisTeamContestChanging(byte value);
    partial void OnisTeamContestChanged();
    partial void OnisSingleContestChanging(byte value);
    partial void OnisSingleContestChanged();
    partial void OnsubmitTimeChanging(System.DateTime value);
    partial void OnsubmitTimeChanged();
    partial void OncodePriorityChanging(int value);
    partial void OncodePriorityChanged();
    #endregion
		
		public CompileCacheModels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cacheCodeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cacheCodeId
		{
			get
			{
				return this._cacheCodeId;
			}
			set
			{
				if ((this._cacheCodeId != value))
				{
					this.OncacheCodeIdChanging(value);
					this.SendPropertyChanging();
					this._cacheCodeId = value;
					this.SendPropertyChanged("cacheCodeId");
					this.OncacheCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeType", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codeType
		{
			get
			{
				return this._codeType;
			}
			set
			{
				if ((this._codeType != value))
				{
					this.OncodeTypeChanging(value);
					this.SendPropertyChanging();
					this._codeType = value;
					this.SendPropertyChanged("codeType");
					this.OncodeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cacheCodeFileName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string cacheCodeFileName
		{
			get
			{
				return this._cacheCodeFileName;
			}
			set
			{
				if ((this._cacheCodeFileName != value))
				{
					this.OncacheCodeFileNameChanging(value);
					this.SendPropertyChanging();
					this._cacheCodeFileName = value;
					this.SendPropertyChanged("cacheCodeFileName");
					this.OncacheCodeFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memoryLimit", DbType="Int NOT NULL")]
		public int memoryLimit
		{
			get
			{
				return this._memoryLimit;
			}
			set
			{
				if ((this._memoryLimit != value))
				{
					this.OnmemoryLimitChanging(value);
					this.SendPropertyChanging();
					this._memoryLimit = value;
					this.SendPropertyChanged("memoryLimit");
					this.OnmemoryLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeLimit", DbType="Int NOT NULL")]
		public int timeLimit
		{
			get
			{
				return this._timeLimit;
			}
			set
			{
				if ((this._timeLimit != value))
				{
					this.OntimeLimitChanging(value);
					this.SendPropertyChanging();
					this._timeLimit = value;
					this.SendPropertyChanged("timeLimit");
					this.OntimeLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int NOT NULL")]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problemId", DbType="Int NOT NULL")]
		public int problemId
		{
			get
			{
				return this._problemId;
			}
			set
			{
				if ((this._problemId != value))
				{
					this.OnproblemIdChanging(value);
					this.SendPropertyChanging();
					this._problemId = value;
					this.SendPropertyChanged("problemId");
					this.OnproblemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentId", DbType="Int")]
		public System.Nullable<int> contentId
		{
			get
			{
				return this._contentId;
			}
			set
			{
				if ((this._contentId != value))
				{
					this.OncontentIdChanging(value);
					this.SendPropertyChanging();
					this._contentId = value;
					this.SendPropertyChanged("contentId");
					this.OncontentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultId", DbType="Int NOT NULL")]
		public int resultId
		{
			get
			{
				return this._resultId;
			}
			set
			{
				if ((this._resultId != value))
				{
					this.OnresultIdChanging(value);
					this.SendPropertyChanging();
					this._resultId = value;
					this.SendPropertyChanged("resultId");
					this.OnresultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTeamContest", DbType="TinyInt NOT NULL")]
		public byte isTeamContest
		{
			get
			{
				return this._isTeamContest;
			}
			set
			{
				if ((this._isTeamContest != value))
				{
					this.OnisTeamContestChanging(value);
					this.SendPropertyChanging();
					this._isTeamContest = value;
					this.SendPropertyChanged("isTeamContest");
					this.OnisTeamContestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSingleContest", DbType="TinyInt NOT NULL")]
		public byte isSingleContest
		{
			get
			{
				return this._isSingleContest;
			}
			set
			{
				if ((this._isSingleContest != value))
				{
					this.OnisSingleContestChanging(value);
					this.SendPropertyChanging();
					this._isSingleContest = value;
					this.SendPropertyChanged("isSingleContest");
					this.OnisSingleContestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_submitTime", DbType="DateTime NOT NULL")]
		public System.DateTime submitTime
		{
			get
			{
				return this._submitTime;
			}
			set
			{
				if ((this._submitTime != value))
				{
					this.OnsubmitTimeChanging(value);
					this.SendPropertyChanging();
					this._submitTime = value;
					this.SendPropertyChanged("submitTime");
					this.OnsubmitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codePriority", DbType="Int NOT NULL")]
		public int codePriority
		{
			get
			{
				return this._codePriority;
			}
			set
			{
				if ((this._codePriority != value))
				{
					this.OncodePriorityChanging(value);
					this.SendPropertyChanging();
					this._codePriority = value;
					this.SendPropertyChanged("codePriority");
					this.OncodePriorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResultModels")]
	public partial class ResultModels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _resut_id;
		
		private string _result_status;
		
		private int _result_memory;
		
		private int _result_time;
		
		private string _result_language;
		
		private System.DateTime _result_submitTime;
		
		private int _result_codeLength;
		
		private int _userId;
		
		private int _resultCodeId;
		
		private int _baseProblemId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onresut_idChanging(int value);
    partial void Onresut_idChanged();
    partial void Onresult_statusChanging(string value);
    partial void Onresult_statusChanged();
    partial void Onresult_memoryChanging(int value);
    partial void Onresult_memoryChanged();
    partial void Onresult_timeChanging(int value);
    partial void Onresult_timeChanged();
    partial void Onresult_languageChanging(string value);
    partial void Onresult_languageChanged();
    partial void Onresult_submitTimeChanging(System.DateTime value);
    partial void Onresult_submitTimeChanged();
    partial void Onresult_codeLengthChanging(int value);
    partial void Onresult_codeLengthChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnresultCodeIdChanging(int value);
    partial void OnresultCodeIdChanged();
    partial void OnbaseProblemIdChanging(int value);
    partial void OnbaseProblemIdChanged();
    #endregion
		
		public ResultModels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resut_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int resut_id
		{
			get
			{
				return this._resut_id;
			}
			set
			{
				if ((this._resut_id != value))
				{
					this.Onresut_idChanging(value);
					this.SendPropertyChanging();
					this._resut_id = value;
					this.SendPropertyChanged("resut_id");
					this.Onresut_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_status", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string result_status
		{
			get
			{
				return this._result_status;
			}
			set
			{
				if ((this._result_status != value))
				{
					this.Onresult_statusChanging(value);
					this.SendPropertyChanging();
					this._result_status = value;
					this.SendPropertyChanged("result_status");
					this.Onresult_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_memory", DbType="Int NOT NULL")]
		public int result_memory
		{
			get
			{
				return this._result_memory;
			}
			set
			{
				if ((this._result_memory != value))
				{
					this.Onresult_memoryChanging(value);
					this.SendPropertyChanging();
					this._result_memory = value;
					this.SendPropertyChanged("result_memory");
					this.Onresult_memoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_time", DbType="Int NOT NULL")]
		public int result_time
		{
			get
			{
				return this._result_time;
			}
			set
			{
				if ((this._result_time != value))
				{
					this.Onresult_timeChanging(value);
					this.SendPropertyChanging();
					this._result_time = value;
					this.SendPropertyChanged("result_time");
					this.Onresult_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_language", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string result_language
		{
			get
			{
				return this._result_language;
			}
			set
			{
				if ((this._result_language != value))
				{
					this.Onresult_languageChanging(value);
					this.SendPropertyChanging();
					this._result_language = value;
					this.SendPropertyChanged("result_language");
					this.Onresult_languageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_submitTime", DbType="DateTime NOT NULL")]
		public System.DateTime result_submitTime
		{
			get
			{
				return this._result_submitTime;
			}
			set
			{
				if ((this._result_submitTime != value))
				{
					this.Onresult_submitTimeChanging(value);
					this.SendPropertyChanging();
					this._result_submitTime = value;
					this.SendPropertyChanged("result_submitTime");
					this.Onresult_submitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_codeLength", DbType="Int NOT NULL")]
		public int result_codeLength
		{
			get
			{
				return this._result_codeLength;
			}
			set
			{
				if ((this._result_codeLength != value))
				{
					this.Onresult_codeLengthChanging(value);
					this.SendPropertyChanging();
					this._result_codeLength = value;
					this.SendPropertyChanged("result_codeLength");
					this.Onresult_codeLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultCodeId", DbType="Int NOT NULL")]
		public int resultCodeId
		{
			get
			{
				return this._resultCodeId;
			}
			set
			{
				if ((this._resultCodeId != value))
				{
					this.OnresultCodeIdChanging(value);
					this.SendPropertyChanging();
					this._resultCodeId = value;
					this.SendPropertyChanged("resultCodeId");
					this.OnresultCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseProblemId", DbType="Int NOT NULL")]
		public int baseProblemId
		{
			get
			{
				return this._baseProblemId;
			}
			set
			{
				if ((this._baseProblemId != value))
				{
					this.OnbaseProblemIdChanging(value);
					this.SendPropertyChanging();
					this._baseProblemId = value;
					this.SendPropertyChanged("baseProblemId");
					this.OnbaseProblemIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaseProblemModels")]
	public partial class BaseProblemModels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pid;
		
		private string _title;
		
		private string _content;
		
		private string _input;
		
		private string _output;
		
		private string _sampleInput;
		
		private string _sampleOutput;
		
		private int _memory_limit;
		
		private int _time_limit;
		
		private int _accepteds;
		
		private int _submiteds;
		
		private int _sourceId;
		
		private int _modelProblemId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpidChanging(int value);
    partial void OnpidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OninputChanging(string value);
    partial void OninputChanged();
    partial void OnoutputChanging(string value);
    partial void OnoutputChanged();
    partial void OnsampleInputChanging(string value);
    partial void OnsampleInputChanged();
    partial void OnsampleOutputChanging(string value);
    partial void OnsampleOutputChanged();
    partial void Onmemory_limitChanging(int value);
    partial void Onmemory_limitChanged();
    partial void Ontime_limitChanging(int value);
    partial void Ontime_limitChanged();
    partial void OnacceptedsChanging(int value);
    partial void OnacceptedsChanged();
    partial void OnsubmitedsChanging(int value);
    partial void OnsubmitedsChanged();
    partial void OnsourceIdChanging(int value);
    partial void OnsourceIdChanged();
    partial void OnmodelProblemIdChanging(int value);
    partial void OnmodelProblemIdChanged();
    #endregion
		
		public BaseProblemModels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string input
		{
			get
			{
				return this._input;
			}
			set
			{
				if ((this._input != value))
				{
					this.OninputChanging(value);
					this.SendPropertyChanging();
					this._input = value;
					this.SendPropertyChanged("input");
					this.OninputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_output", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string output
		{
			get
			{
				return this._output;
			}
			set
			{
				if ((this._output != value))
				{
					this.OnoutputChanging(value);
					this.SendPropertyChanging();
					this._output = value;
					this.SendPropertyChanged("output");
					this.OnoutputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sampleInput", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string sampleInput
		{
			get
			{
				return this._sampleInput;
			}
			set
			{
				if ((this._sampleInput != value))
				{
					this.OnsampleInputChanging(value);
					this.SendPropertyChanging();
					this._sampleInput = value;
					this.SendPropertyChanged("sampleInput");
					this.OnsampleInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sampleOutput", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string sampleOutput
		{
			get
			{
				return this._sampleOutput;
			}
			set
			{
				if ((this._sampleOutput != value))
				{
					this.OnsampleOutputChanging(value);
					this.SendPropertyChanging();
					this._sampleOutput = value;
					this.SendPropertyChanged("sampleOutput");
					this.OnsampleOutputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memory_limit", DbType="Int NOT NULL")]
		public int memory_limit
		{
			get
			{
				return this._memory_limit;
			}
			set
			{
				if ((this._memory_limit != value))
				{
					this.Onmemory_limitChanging(value);
					this.SendPropertyChanging();
					this._memory_limit = value;
					this.SendPropertyChanged("memory_limit");
					this.Onmemory_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_limit", DbType="Int NOT NULL")]
		public int time_limit
		{
			get
			{
				return this._time_limit;
			}
			set
			{
				if ((this._time_limit != value))
				{
					this.Ontime_limitChanging(value);
					this.SendPropertyChanging();
					this._time_limit = value;
					this.SendPropertyChanged("time_limit");
					this.Ontime_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accepteds", DbType="Int NOT NULL")]
		public int accepteds
		{
			get
			{
				return this._accepteds;
			}
			set
			{
				if ((this._accepteds != value))
				{
					this.OnacceptedsChanging(value);
					this.SendPropertyChanging();
					this._accepteds = value;
					this.SendPropertyChanged("accepteds");
					this.OnacceptedsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_submiteds", DbType="Int NOT NULL")]
		public int submiteds
		{
			get
			{
				return this._submiteds;
			}
			set
			{
				if ((this._submiteds != value))
				{
					this.OnsubmitedsChanging(value);
					this.SendPropertyChanging();
					this._submiteds = value;
					this.SendPropertyChanged("submiteds");
					this.OnsubmitedsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="Int NOT NULL")]
		public int sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelProblemId", DbType="Int NOT NULL")]
		public int modelProblemId
		{
			get
			{
				return this._modelProblemId;
			}
			set
			{
				if ((this._modelProblemId != value))
				{
					this.OnmodelProblemIdChanging(value);
					this.SendPropertyChanging();
					this._modelProblemId = value;
					this.SendPropertyChanged("modelProblemId");
					this.OnmodelProblemIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SingleResultModels")]
	public partial class SingleResultModels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _singleResutId;
		
		private string _singleResultStatus;
		
		private int _singleResultMemory;
		
		private int _singleResultTime;
		
		private string _singleResultLanguage;
		
		private System.DateTime _singleResultSubmitTime;
		
		private int _singleResultCodeLength;
		
		private int _singleContestId;
		
		private int _baseProblemId;
		
		private int _userId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsingleResutIdChanging(int value);
    partial void OnsingleResutIdChanged();
    partial void OnsingleResultStatusChanging(string value);
    partial void OnsingleResultStatusChanged();
    partial void OnsingleResultMemoryChanging(int value);
    partial void OnsingleResultMemoryChanged();
    partial void OnsingleResultTimeChanging(int value);
    partial void OnsingleResultTimeChanged();
    partial void OnsingleResultLanguageChanging(string value);
    partial void OnsingleResultLanguageChanged();
    partial void OnsingleResultSubmitTimeChanging(System.DateTime value);
    partial void OnsingleResultSubmitTimeChanged();
    partial void OnsingleResultCodeLengthChanging(int value);
    partial void OnsingleResultCodeLengthChanged();
    partial void OnsingleContestIdChanging(int value);
    partial void OnsingleContestIdChanged();
    partial void OnbaseProblemIdChanging(int value);
    partial void OnbaseProblemIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public SingleResultModels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResutId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int singleResutId
		{
			get
			{
				return this._singleResutId;
			}
			set
			{
				if ((this._singleResutId != value))
				{
					this.OnsingleResutIdChanging(value);
					this.SendPropertyChanging();
					this._singleResutId = value;
					this.SendPropertyChanged("singleResutId");
					this.OnsingleResutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultStatus", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string singleResultStatus
		{
			get
			{
				return this._singleResultStatus;
			}
			set
			{
				if ((this._singleResultStatus != value))
				{
					this.OnsingleResultStatusChanging(value);
					this.SendPropertyChanging();
					this._singleResultStatus = value;
					this.SendPropertyChanged("singleResultStatus");
					this.OnsingleResultStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultMemory", DbType="Int NOT NULL")]
		public int singleResultMemory
		{
			get
			{
				return this._singleResultMemory;
			}
			set
			{
				if ((this._singleResultMemory != value))
				{
					this.OnsingleResultMemoryChanging(value);
					this.SendPropertyChanging();
					this._singleResultMemory = value;
					this.SendPropertyChanged("singleResultMemory");
					this.OnsingleResultMemoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultTime", DbType="Int NOT NULL")]
		public int singleResultTime
		{
			get
			{
				return this._singleResultTime;
			}
			set
			{
				if ((this._singleResultTime != value))
				{
					this.OnsingleResultTimeChanging(value);
					this.SendPropertyChanging();
					this._singleResultTime = value;
					this.SendPropertyChanged("singleResultTime");
					this.OnsingleResultTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultLanguage", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string singleResultLanguage
		{
			get
			{
				return this._singleResultLanguage;
			}
			set
			{
				if ((this._singleResultLanguage != value))
				{
					this.OnsingleResultLanguageChanging(value);
					this.SendPropertyChanging();
					this._singleResultLanguage = value;
					this.SendPropertyChanged("singleResultLanguage");
					this.OnsingleResultLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultSubmitTime", DbType="DateTime NOT NULL")]
		public System.DateTime singleResultSubmitTime
		{
			get
			{
				return this._singleResultSubmitTime;
			}
			set
			{
				if ((this._singleResultSubmitTime != value))
				{
					this.OnsingleResultSubmitTimeChanging(value);
					this.SendPropertyChanging();
					this._singleResultSubmitTime = value;
					this.SendPropertyChanged("singleResultSubmitTime");
					this.OnsingleResultSubmitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleResultCodeLength", DbType="Int NOT NULL")]
		public int singleResultCodeLength
		{
			get
			{
				return this._singleResultCodeLength;
			}
			set
			{
				if ((this._singleResultCodeLength != value))
				{
					this.OnsingleResultCodeLengthChanging(value);
					this.SendPropertyChanging();
					this._singleResultCodeLength = value;
					this.SendPropertyChanged("singleResultCodeLength");
					this.OnsingleResultCodeLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singleContestId", DbType="Int NOT NULL")]
		public int singleContestId
		{
			get
			{
				return this._singleContestId;
			}
			set
			{
				if ((this._singleContestId != value))
				{
					this.OnsingleContestIdChanging(value);
					this.SendPropertyChanging();
					this._singleContestId = value;
					this.SendPropertyChanged("singleContestId");
					this.OnsingleContestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseProblemId", DbType="Int NOT NULL")]
		public int baseProblemId
		{
			get
			{
				return this._baseProblemId;
			}
			set
			{
				if ((this._baseProblemId != value))
				{
					this.OnbaseProblemIdChanging(value);
					this.SendPropertyChanging();
					this._baseProblemId = value;
					this.SendPropertyChanged("baseProblemId");
					this.OnbaseProblemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeamResultModels")]
	public partial class TeamResultModels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teamResutId;
		
		private string _teamResultStatus;
		
		private int _teamResultMemory;
		
		private int _teamResultTime;
		
		private string _teamResultLanguage;
		
		private System.DateTime _teamResultSubmitTime;
		
		private int _teamResultCodeLength;
		
		private int _teamContestId;
		
		private int _baseProblemId;
		
		private int _teamId;
		
		private int _userId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnteamResutIdChanging(int value);
    partial void OnteamResutIdChanged();
    partial void OnteamResultStatusChanging(string value);
    partial void OnteamResultStatusChanged();
    partial void OnteamResultMemoryChanging(int value);
    partial void OnteamResultMemoryChanged();
    partial void OnteamResultTimeChanging(int value);
    partial void OnteamResultTimeChanged();
    partial void OnteamResultLanguageChanging(string value);
    partial void OnteamResultLanguageChanged();
    partial void OnteamResultSubmitTimeChanging(System.DateTime value);
    partial void OnteamResultSubmitTimeChanged();
    partial void OnteamResultCodeLengthChanging(int value);
    partial void OnteamResultCodeLengthChanged();
    partial void OnteamContestIdChanging(int value);
    partial void OnteamContestIdChanged();
    partial void OnbaseProblemIdChanging(int value);
    partial void OnbaseProblemIdChanged();
    partial void OnteamIdChanging(int value);
    partial void OnteamIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public TeamResultModels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResutId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teamResutId
		{
			get
			{
				return this._teamResutId;
			}
			set
			{
				if ((this._teamResutId != value))
				{
					this.OnteamResutIdChanging(value);
					this.SendPropertyChanging();
					this._teamResutId = value;
					this.SendPropertyChanged("teamResutId");
					this.OnteamResutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultStatus", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string teamResultStatus
		{
			get
			{
				return this._teamResultStatus;
			}
			set
			{
				if ((this._teamResultStatus != value))
				{
					this.OnteamResultStatusChanging(value);
					this.SendPropertyChanging();
					this._teamResultStatus = value;
					this.SendPropertyChanged("teamResultStatus");
					this.OnteamResultStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultMemory", DbType="Int NOT NULL")]
		public int teamResultMemory
		{
			get
			{
				return this._teamResultMemory;
			}
			set
			{
				if ((this._teamResultMemory != value))
				{
					this.OnteamResultMemoryChanging(value);
					this.SendPropertyChanging();
					this._teamResultMemory = value;
					this.SendPropertyChanged("teamResultMemory");
					this.OnteamResultMemoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultTime", DbType="Int NOT NULL")]
		public int teamResultTime
		{
			get
			{
				return this._teamResultTime;
			}
			set
			{
				if ((this._teamResultTime != value))
				{
					this.OnteamResultTimeChanging(value);
					this.SendPropertyChanging();
					this._teamResultTime = value;
					this.SendPropertyChanged("teamResultTime");
					this.OnteamResultTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultLanguage", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string teamResultLanguage
		{
			get
			{
				return this._teamResultLanguage;
			}
			set
			{
				if ((this._teamResultLanguage != value))
				{
					this.OnteamResultLanguageChanging(value);
					this.SendPropertyChanging();
					this._teamResultLanguage = value;
					this.SendPropertyChanged("teamResultLanguage");
					this.OnteamResultLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultSubmitTime", DbType="DateTime NOT NULL")]
		public System.DateTime teamResultSubmitTime
		{
			get
			{
				return this._teamResultSubmitTime;
			}
			set
			{
				if ((this._teamResultSubmitTime != value))
				{
					this.OnteamResultSubmitTimeChanging(value);
					this.SendPropertyChanging();
					this._teamResultSubmitTime = value;
					this.SendPropertyChanged("teamResultSubmitTime");
					this.OnteamResultSubmitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamResultCodeLength", DbType="Int NOT NULL")]
		public int teamResultCodeLength
		{
			get
			{
				return this._teamResultCodeLength;
			}
			set
			{
				if ((this._teamResultCodeLength != value))
				{
					this.OnteamResultCodeLengthChanging(value);
					this.SendPropertyChanging();
					this._teamResultCodeLength = value;
					this.SendPropertyChanged("teamResultCodeLength");
					this.OnteamResultCodeLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamContestId", DbType="Int NOT NULL")]
		public int teamContestId
		{
			get
			{
				return this._teamContestId;
			}
			set
			{
				if ((this._teamContestId != value))
				{
					this.OnteamContestIdChanging(value);
					this.SendPropertyChanging();
					this._teamContestId = value;
					this.SendPropertyChanged("teamContestId");
					this.OnteamContestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseProblemId", DbType="Int NOT NULL")]
		public int baseProblemId
		{
			get
			{
				return this._baseProblemId;
			}
			set
			{
				if ((this._baseProblemId != value))
				{
					this.OnbaseProblemIdChanging(value);
					this.SendPropertyChanging();
					this._baseProblemId = value;
					this.SendPropertyChanged("baseProblemId");
					this.OnbaseProblemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamId", DbType="Int NOT NULL")]
		public int teamId
		{
			get
			{
				return this._teamId;
			}
			set
			{
				if ((this._teamId != value))
				{
					this.OnteamIdChanging(value);
					this.SendPropertyChanging();
					this._teamId = value;
					this.SendPropertyChanged("teamId");
					this.OnteamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
