//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coder.CompilerOfOJ.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coder.CompilerOfOJ.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 gcc 的本地化字符串。
        /// </summary>
        internal static string COMPILER_C {
            get {
                return ResourceManager.GetString("COMPILER_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 g++ 的本地化字符串。
        /// </summary>
        internal static string COMPILER_CPLUSPLUS {
            get {
                return ResourceManager.GetString("COMPILER_CPLUSPLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 javac 的本地化字符串。
        /// </summary>
        internal static string COMPILER_JAVA {
            get {
                return ResourceManager.GetString("COMPILER_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string CONTEST_NOT_A {
            get {
                return ResourceManager.GetString("CONTEST_NOT_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string CONTEST_SINGLE {
            get {
                return ResourceManager.GetString("CONTEST_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string CONTEST_TEAM {
            get {
                return ResourceManager.GetString("CONTEST_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bad compiler 的本地化字符串。
        /// </summary>
        internal static string ERROR_COMPILER {
            get {
                return ResourceManager.GetString("ERROR_COMPILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bad run 的本地化字符串。
        /// </summary>
        internal static string ERROR_RUN {
            get {
                return ResourceManager.GetString("ERROR_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .txt 的本地化字符串。
        /// </summary>
        internal static string EXTENTION {
            get {
                return ResourceManager.GetString("EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string LANGUE_C {
            get {
                return ResourceManager.GetString("LANGUE_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C++ 的本地化字符串。
        /// </summary>
        internal static string LANGUE_CPLUSPLUS {
            get {
                return ResourceManager.GetString("LANGUE_CPLUSPLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c# 的本地化字符串。
        /// </summary>
        internal static string LANGUE_CSHARP {
            get {
                return ResourceManager.GetString("LANGUE_CSHARP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JAVA 的本地化字符串。
        /// </summary>
        internal static string LANGUE_JAVA {
            get {
                return ResourceManager.GetString("LANGUE_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACCEPTED 的本地化字符串。
        /// </summary>
        internal static string RESULT_ACCEPTED {
            get {
                return ResourceManager.GetString("RESULT_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COMPILE_ERROR 的本地化字符串。
        /// </summary>
        internal static string RESULT_COMPILE_ERROR {
            get {
                return ResourceManager.GetString("RESULT_COMPILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DANGEROUS 的本地化字符串。
        /// </summary>
        internal static string RESULT_DANGEROUS {
            get {
                return ResourceManager.GetString("RESULT_DANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INNER_ERROR 的本地化字符串。
        /// </summary>
        internal static string RESULT_INNER_ERROR {
            get {
                return ResourceManager.GetString("RESULT_INNER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MEMORY_LIMIT_EXCEED 的本地化字符串。
        /// </summary>
        internal static string RESULT_MEMORY_LIMIT_EXCEED {
            get {
                return ResourceManager.GetString("RESULT_MEMORY_LIMIT_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRESENTATION_ERROR 的本地化字符串。
        /// </summary>
        internal static string RESULT_PRESENTATION_ERROR {
            get {
                return ResourceManager.GetString("RESULT_PRESENTATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QUEUING 的本地化字符串。
        /// </summary>
        internal static string RESULT_QUEUING {
            get {
                return ResourceManager.GetString("RESULT_QUEUING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RUNTIME_ERROR 的本地化字符串。
        /// </summary>
        internal static string RESULT_RUNTIME_ERROR {
            get {
                return ResourceManager.GetString("RESULT_RUNTIME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIME_LIMIT_EXCEED 的本地化字符串。
        /// </summary>
        internal static string RESULT_TIME_LIMIT_EXCEED {
            get {
                return ResourceManager.GetString("RESULT_TIME_LIMIT_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WRONG_ANSWER 的本地化字符串。
        /// </summary>
        internal static string RESULT_WRONG_ANSWER {
            get {
                return ResourceManager.GetString("RESULT_WRONG_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E:/OJFiles/ 的本地化字符串。
        /// </summary>
        internal static string ROOT_PATH {
            get {
                return ResourceManager.GetString("ROOT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E:/OJFiles/Ins/ 的本地化字符串。
        /// </summary>
        internal static string ROOT_STANDARD_IN_PATH {
            get {
                return ResourceManager.GetString("ROOT_STANDARD_IN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E:/OJFiles/Outs/ 的本地化字符串。
        /// </summary>
        internal static string ROOT_STANDARD_OUT_PATH {
            get {
                return ResourceManager.GetString("ROOT_STANDARD_OUT_PATH", resourceCulture);
            }
        }
    }
}
